# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Convert HDF5 dataset to GR00T LeRobot dataset format.

This script converts HDF5 files generated by data_recorder.py to the GR00T LeRobot
dataset format, which is compatible with NVIDIA Isaac GR00T training pipelines.

Reference: https://github.com/NVIDIA/Isaac-GR00T/blob/main/getting_started/LeRobot_compatible_data_schema.md

Output structure:
    <output_dir>/
    ├── meta/
    │   ├── episodes.jsonl
    │   ├── modality.json
    │   ├── info.json
    │   └── tasks.jsonl
    ├── videos/
    │   └── chunk-000/
    │       └── observation.images.<camera_name>/
    │           └── episode_XXXXXX.mp4
    └── data/
        └── chunk-000/
            └── episode_XXXXXX.parquet

Usage:
    python scripts/convert_to_gr00t.py --input /tmp/dummy_agent/data.h5 --output /tmp/gr00t_dataset
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import cv2
import h5py
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq


@dataclass
class ModalityConfig:
    """Configuration for state/action modalities."""

    state: dict[str, dict[str, Any]] = field(default_factory=dict)
    action: dict[str, dict[str, Any]] = field(default_factory=dict)
    video: dict[str, dict[str, str]] = field(default_factory=dict)
    annotation: dict[str, dict] = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        result = {}
        if self.state:
            result["state"] = self.state
        if self.action:
            result["action"] = self.action
        if self.video:
            result["video"] = self.video
        if self.annotation:
            result["annotation"] = self.annotation
        return result


def infer_modality_config(h5_file: h5py.File) -> ModalityConfig:
    """Infer modality configuration from HDF5 file structure.

    Args:
        h5_file: Open HDF5 file.

    Returns:
        ModalityConfig with inferred state/action/video mappings.
    """
    config = ModalityConfig()

    # Get first demo to inspect structure
    data_grp = h5_file["data"]
    demo_names = [k for k in data_grp.keys() if k.startswith("demo_")]
    if not demo_names:
        raise ValueError("No demos found in HDF5 file")

    demo = data_grp[demo_names[0]]

    # Infer state modalities from observations
    if "obs" in demo:
        obs_grp = demo["obs"]
        state_idx = 0

        for obs_name in obs_grp.keys():
            obs_data = obs_grp[obs_name]
            shape = obs_data.shape

            # Check if it's an image (3D or 4D array with last dim being channels)
            if len(shape) >= 3 and shape[-1] in [1, 3, 4]:
                # This is likely a video/image observation
                config.video[obs_name] = {"original_key": f"observation.images.{obs_name}"}
            else:
                # This is a state observation
                if len(shape) == 2:
                    dim = shape[1]
                elif len(shape) == 1:
                    dim = 1
                else:
                    dim = int(np.prod(shape[1:]))

                config.state[obs_name] = {"start": state_idx, "end": state_idx + dim}
                state_idx += dim

    # Infer action modalities
    if "actions" in demo:
        action_data = demo["actions"]
        action_dim = action_data.shape[1] if len(action_data.shape) > 1 else 1
        config.action["action"] = {"start": 0, "end": action_dim}

    # Add default annotation
    config.annotation["human.action.task_description"] = {}

    return config


def images_to_video(images: np.ndarray, output_path: Path, fps: int = 30, debug: bool = False) -> None:
    """Convert a sequence of images to an MP4 video.

    Args:
        images: Array of images with shape (N, H, W, C) or (N, C, H, W).
        output_path: Path to save the video.
        fps: Frames per second.
        debug: If True, print debug information about the image data.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if len(images) == 0:
        return

    images = np.array(images, dtype=np.float32)

    if debug:
        print(f"    Original shape: {images.shape}, dtype: {images.dtype}")
        print(f"    Value range: [{images.min():.3f}, {images.max():.3f}]")

    # Handle channel-first format (N, C, H, W) -> (N, H, W, C)
    # Detect by checking if dim 1 is small (1, 3, or 4) and dim 3 is also small
    if len(images.shape) == 4:
        if images.shape[1] in [1, 3, 4] and images.shape[3] not in [1, 3, 4]:
            images = np.transpose(images, (0, 2, 3, 1))
            if debug:
                print(f"    Transposed to: {images.shape}")

    height, width = images.shape[1:3]
    num_channels = images.shape[3] if len(images.shape) == 4 else 1

    if debug:
        print(f"    Video size: {width}x{height}, channels: {num_channels}")

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(output_path), fourcc, fps, (width, height))

    if not writer.isOpened():
        raise RuntimeError(f"Failed to open VideoWriter for {output_path} (size={width}x{height}, codec=mp4v)")

    for i, img in enumerate(images):
        img = img.astype(np.float32)

        # Normalize to 0-255 range
        img_min, img_max = img.min(), img.max()
        if img_max > img_min:
            if img_min >= 0.0 and img_max <= 1.0:
                # Normalized [0, 1]
                img = img * 255.0
            elif img_min >= 0.0 and img_max <= 255.0:
                # Already in [0, 255] range
                pass
            else:
                # Arbitrary range (e.g., [-1, 1]) — normalize to [0, 255]
                img = (img - img_min) / (img_max - img_min) * 255.0

        img = np.clip(img, 0, 255).astype(np.uint8)

        # Convert color space for OpenCV (RGB -> BGR)
        if len(img.shape) == 3:
            if img.shape[-1] == 3:
                img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
            elif img.shape[-1] == 4:
                img = cv2.cvtColor(img, cv2.COLOR_RGBA2BGR)
            elif img.shape[-1] == 1:
                img = np.squeeze(img, axis=-1)
                img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
        elif len(img.shape) == 2:
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

        if i == 0 and debug:
            print(f"    First frame after processing: shape={img.shape}, range=[{img.min()}, {img.max()}]")

        writer.write(img)

    writer.release()


def convert_hdf5_to_gr00t(
    input_path: str | Path,
    output_path: str | Path,
    task_description: str = "robot manipulation task",
    fps: int = 30,
    modality_config: ModalityConfig | None = None,
) -> None:
    """Convert HDF5 dataset to GR00T LeRobot format.

    Args:
        input_path: Path to input HDF5 file.
        output_path: Path to output directory.
        task_description: Default task description for all episodes.
        fps: Frames per second for video encoding.
        modality_config: Optional custom modality configuration.
    """
    input_path = Path(input_path)
    output_path = Path(output_path)

    # Create output directories
    meta_dir = output_path / "meta"
    data_dir = output_path / "data" / "chunk-000"
    video_dir = output_path / "videos" / "chunk-000"

    meta_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    print(f"Converting {input_path} to GR00T format at {output_path}")

    with h5py.File(input_path, "r") as h5_file:
        # Infer or use provided modality config
        if modality_config is None:
            modality_config = infer_modality_config(h5_file)

        data_grp = h5_file["data"]
        demo_names = sorted(
            [k for k in data_grp.keys() if k.startswith("demo_")],
            key=lambda x: int(x.split("_")[1]),
        )

        # Prepare metadata collectors
        episodes_info = []
        tasks_set = {task_description}  # Use set to track unique tasks
        global_index = 0

        # Track dimensions for features metadata
        state_dim = 0
        action_dim = 0
        video_height = 0
        video_width = 0

        # Process each demo
        for demo_idx, demo_name in enumerate(demo_names):
            demo = data_grp[demo_name]
            num_samples = int(demo.attrs.get("num_samples", 0))

            if num_samples == 0:
                # Try to infer from data
                if "obs" in demo:
                    first_obs = next(iter(demo["obs"].values()))
                    num_samples = int(len(first_obs))
                else:
                    continue

            print(f"  Processing {demo_name} ({num_samples} samples)")

            # Collect state observations
            state_arrays = []
            video_obs = {}

            if "obs" in demo:
                for obs_name, obs_data in demo["obs"].items():
                    data = obs_data[:]

                    # Check if video
                    if obs_name in modality_config.video:
                        video_obs[obs_name] = data
                    else:
                        # Flatten to 2D if needed
                        if len(data.shape) > 2:
                            data = data.reshape(data.shape[0], -1)
                        elif len(data.shape) == 1:
                            data = data.reshape(-1, 1)
                        state_arrays.append(data)

            # Concatenate states
            if state_arrays:
                observation_state = np.concatenate(state_arrays, axis=1).astype(np.float32)
            else:
                observation_state = np.zeros((num_samples, 0), dtype=np.float32)

            # Track state dimension (from first demo)
            if demo_idx == 0:
                state_dim = observation_state.shape[1]

            # Get actions
            if "actions" in demo:
                actions = demo["actions"][:].astype(np.float32)
                if len(actions.shape) == 1:
                    actions = actions.reshape(-1, 1)
            else:
                actions = np.zeros((num_samples, 0), dtype=np.float32)

            # Track action dimension (from first demo)
            if demo_idx == 0:
                action_dim = actions.shape[1] if len(actions.shape) > 1 else 1

            # Track video dimensions (from first demo with video)
            if demo_idx == 0 and video_obs:
                first_video = next(iter(video_obs.values()))
                if len(first_video.shape) >= 3:
                    video_height = first_video.shape[1]
                    video_width = first_video.shape[2]

            # Create parquet data
            records = []
            for i in range(num_samples):
                record = {
                    "observation.state": observation_state[i].tolist(),
                    "action": actions[i].tolist() if i < len(actions) else [],
                    "timestamp": float(i) / fps,
                    "annotation.human.action.task_description": 0,  # Task index
                    "task_index": 0,
                    "episode_index": demo_idx,
                    "index": global_index,
                    "next.reward": 0.0,
                    "next.done": i == num_samples - 1,
                }
                records.append(record)
                global_index += 1

            # Write parquet file
            episode_file = data_dir / f"episode_{demo_idx:06d}.parquet"
            table = pa.Table.from_pylist(records)
            pq.write_table(table, episode_file)

            # Write video files
            for video_name, video_data in video_obs.items():
                video_subdir = video_dir / f"observation.images.{video_name}"
                video_file = video_subdir / f"episode_{demo_idx:06d}.mp4"
                # Enable debug for first episode to show image data info
                images_to_video(video_data, video_file, fps=fps, debug=(demo_idx == 0))

            # Record episode info
            episodes_info.append(
                {
                    "episode_index": demo_idx,
                    "tasks": [task_description],
                    "length": num_samples,
                }
            )

        # Write meta/tasks.jsonl
        tasks_file = meta_dir / "tasks.jsonl"
        with open(tasks_file, "w") as f:
            for idx, task in enumerate(sorted(tasks_set)):
                f.write(json.dumps({"task_index": idx, "task": task}) + "\n")

        # Write meta/episodes.jsonl
        episodes_file = meta_dir / "episodes.jsonl"
        with open(episodes_file, "w") as f:
            for ep_info in episodes_info:
                f.write(json.dumps(ep_info) + "\n")

        # Write meta/modality.json
        modality_file = meta_dir / "modality.json"
        with open(modality_file, "w") as f:
            json.dump(modality_config.to_dict(), f, indent=2)

        # Build features dict for info.json (required by LeRobot/GR00T)
        features = {
            "observation.state": {
                "dtype": "float32",
                "shape": [state_dim] if state_dim > 0 else [1],
                "names": list(modality_config.state.keys()),
            },
            "action": {
                "dtype": "float32",
                "shape": [action_dim] if action_dim > 0 else [1],
                "names": list(modality_config.action.keys()),
            },
            "timestamp": {"dtype": "float32", "shape": [1]},
            "episode_index": {"dtype": "int64", "shape": [1]},
            "index": {"dtype": "int64", "shape": [1]},
            "task_index": {"dtype": "int64", "shape": [1]},
            "next.done": {"dtype": "bool", "shape": [1]},
            "next.reward": {"dtype": "float32", "shape": [1]},
        }

        # Add video features
        for video_name in modality_config.video.keys():
            original_key = f"observation.images.{video_name}"
            features[original_key] = {
                "dtype": "video",
                "shape": [video_height if video_height else 224, video_width if video_width else 224, 3],
                "names": ["height", "width", "channels"],
                "info": {
                    "video.fps": float(fps),
                    "video.height": video_height if video_height else 224,
                    "video.width": video_width if video_width else 224,
                    "video.channels": 3,
                    "video.codec": "mp4v",
                    "video.pix_fmt": "rgb24",
                    "has_audio": False,
                },
            }

        # Add annotation features
        for anno_key in modality_config.annotation.keys():
            features[f"annotation.{anno_key}"] = {"dtype": "int64", "shape": [1]}

        # Write meta/info.json
        info = {
            "codebase_version": "v2.0",
            "robot_type": "g1_humanoid",
            "total_episodes": len(episodes_info),
            "total_frames": global_index,
            "total_chunks": 1,
            "chunks_size": len(episodes_info),
            "fps": fps,
            "splits": {"train": f"0:{len(episodes_info)}"},
            "data_path": "data/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.parquet",
            "video_path": "videos/chunk-{episode_chunk:03d}/{video_key}/episode_{episode_index:06d}.mp4",
            "features": features,
        }
        info_file = meta_dir / "info.json"
        with open(info_file, "w") as f:
            json.dump(info, f, indent=2)

    print("\nConversion complete!")
    print(f"  Episodes: {len(episodes_info)}")
    print(f"  Total frames: {global_index}")
    print(f"  Output: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert HDF5 dataset to GR00T LeRobot format",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/convert_to_gr00t.py --input /tmp/dummy_agent/data.h5 --output /tmp/gr00t_dataset
    python scripts/convert_to_gr00t.py --input data.h5 --output gr00t_data --task "pick up the apple"
        """,
    )
    parser.add_argument(
        "--input",
        "-i",
        type=str,
        required=True,
        help="Path to input HDF5 file",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        required=True,
        help="Path to output directory",
    )
    parser.add_argument(
        "--task",
        "-t",
        type=str,
        default="robot manipulation task",
        help="Task description for the dataset",
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=30,
        help="Frames per second for video encoding (default: 30)",
    )

    args = parser.parse_args()

    convert_hdf5_to_gr00t(
        input_path=args.input,
        output_path=args.output,
        task_description=args.task,
        fps=args.fps,
    )


if __name__ == "__main__":
    main()
